name: geopifu
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=2.14=openblas
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2020.1.1=0
  - cairo=1.16.0=hcf35c78_1003
  - certifi=2020.4.5.1=py36_0
  - cloudpickle=1.4.1=py_0
  - cudatoolkit=10.0.130=0
  - cycler=0.10.0=py36_0
  - cytoolz=0.10.1=py36h7b6447c_0
  - dask-core=2.17.2=py_0
  - dbus=1.13.14=hb2f20db_0
  - decorator=4.4.2=py_0
  - embree=2.14.0=0
  - expat=2.2.6=he6710b0_0
  - ffmpeg=4.1.3=h167e202_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.9.1=h8a8886c_1
  - giflib=5.2.1=h516909a_2
  - glib=2.63.1=h5a9c865_0
  - gmp=6.2.0=he1b5a44_2
  - gnutls=3.6.13=h79a8f9a_0
  - graphite2=1.3.13=he1b5a44_1001
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - harfbuzz=2.4.0=h9f30f68_3
  - hdf5=1.10.5=nompi_h3c11f04_1104
  - icu=64.2=he1b5a44_1
  - imageio=2.8.0=py_0
  - intel-openmp=2020.1=217
  - jasper=1.900.1=h07fcdf6_1006
  - jpeg=9d=h516909a_0
  - kiwisolver=1.2.0=py36hfd86e86_0
  - lame=3.100=h14c3975_1001
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libclang=9.0.1=default_hde54327_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1006
  - liblapack=3.8.0=14_openblas
  - liblapacke=3.8.0=14_openblas
  - libllvm9=9.0.1=he513fc3_1
  - libopenblas=0.3.7=h5ec1e0e_6
  - libopencv=4.2.0=py36_3
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=2.32.1=h14c3975_1000
  - libwebp=1.0.2=h56121f0_5
  - libxcb=1.13=h1bed415_1
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.9=hea5a465_1
  - lz4-c=1.9.2=he6710b0_0
  - matplotlib=3.2.1=0
  - matplotlib-base=3.2.1=py36hb8e4980_0
  - mkl=2020.1=217
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.0.10=py36_0
  - mkl_random=1.1.1=py36h830a2c2_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.4.1=h1bed415_1002
  - networkx=2.4=py_0
  - ninja=1.9.0=py36hfd86e86_0
  - nspr=4.25=he1b5a44_0
  - nss=3.47=he751ad9_0
  - numpy=1.18.5=py36h7314795_0
  - numpy-base=1.18.1=py36h2f8d375_1
  - olefile=0.46=py_0
  - opencv=4.2.0=py36_3
  - openh264=1.8.0=hdbcaa40_1000
  - openssl=1.1.1g=h7b6447c_0
  - pcre=8.43=he6710b0_0
  - pillow=7.1.2=py36hb39fc2d_0
  - pip=20.0.2=py36_3
  - pixman=0.38.0=h516909a_1003
  - py-opencv=4.2.0=py36h95af2a2_3
  - pyembree=0.1.6=py36h830a2c2_1
  - pyopengl=3.1.1a1=py36_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.12.3=py36haa643ae_3
  - python=3.6.10=hcf32534_1
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytorch=1.4.0=py3.6_cuda10.0.130_cudnn7.6.3_0
  - pywavelets=1.1.1=py36h7b6447c_0
  - pyyaml=5.3.1=py36h7b6447c_0
  - qt=5.12.5=hd8c4c69_1
  - readline=8.0=h7b6447c_0
  - scikit-image=0.16.2=py36h0573a6f_0
  - scipy=1.4.1=py36h2d22cac_3
  - setuptools=47.1.1=py36_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.15.0=py_0
  - sqlite=3.31.1=h62c20be_1
  - tk=8.6.10=hed695b0_0
  - toolz=0.10.0=py_0
  - torchvision=0.5.0=py36_cu100
  - tornado=6.0.4=py36h7b6447c_1
  - tqdm=4.46.0=py_0
  - wheel=0.34.2=py36_0
  - x264=1!152.20180806=h14c3975_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h7b6447c_0
  - yaml=0.1.7=had09818_2
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.4=h0b5b093_3
  - pip:
    - future==0.18.2
    - openexr==1.3.2
    - ptflops==0.6.2
    - pyexr==0.3.8
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - trimesh==3.6.43
prefix: /home/tong/anaconda3/envs/geopifu

